### PR TITLE
Remove beaker cacheing and use custom cacheing

### PR DESCRIPTION
**Pull request by 82ndab-Bravo17**
We've been running this for a week now without any issues

### CODE REVIEW

**Comment by thomasleveil** [comment]
is beaker used elsewhere in B3 or can we also delete its files from `b3/lib`?

**Comment by 82ndab-Bravo17** [comment]
The only other place I can find the word beaker now is inb3.egg-info\SOURCES.txt

**Comment by thomasleveil** [comment]
can you also delete `b3/lib/beaker` then?

**Comment by 82ndab-Bravo17** [comment]
I hope that did it!

**Comment by thomasleveil** [comment]
thx :+1:

**Comment by 82ndab-Bravo17** [comment]
Just realized that I needed to remove beaker refs from SOURCES.txt as well - I'll do that when I get home tonight and send another pull request. I have a couple of Arma and Insurgency updates as well.

**Pull request merged**
