### PR TITLE
Multiline support

### PR DESCRIPTION
**Pull request by lrq3000**
This PR adds optional support for multiline messages in any plugin.

Just add <set name="multiline">on</set> in your b3.xml config below setup server.

Also can use <set name="multiline_noprefix">on</set> to remove the yellow > prefix that is prepended to subsequent lines of a multiline message.

Tested on Q3A.

Here is what it looks like:
3aec5a0f2899f4e415895f6fe48dcd1ff00c4945304cfc4a67 pimgpsh_fullsize_distr

### CODE REVIEW

**Comment by danielepantaleone** [comment]
Does this PR also contains changes from [this](https://github.com/BigBrotherBot/big-brother-bot/pull/369) other one?

**Comment by lrq3000** [comment]
Ah sorry, gonna cleanup later

Le 31 Mai. 2017 09:25, "Daniele Pantaleone" <notifications@github.com> a
écrit :

**Comment by lrq3000** [comment]
Ok fixed, sorry about that :/

**Comment by danielepantaleone** [comment]
Nice one! 👍

**Pull request merged**
