### PR TITLE
setup procedure update

### PR DESCRIPTION
**Pull request by danielepantaleone**
This PR carries some major changes to the console setup procedure:

* removed SQL file import: storage module already provides database table generation when they are found to be missing
* changed add_set and raw_default to accept a reference to a function used to validate input data (return True when the value is accepted, false otherwise): raw_default will also keep asking for the same value until an acceptable one is inserted by the user (also for allow_blank)
* removed extplugins download: this is actually because of more than one reason: (1) links may change and placing them in B3 configuration templates sounds somehow odd to me, (2) I have plans of making a B3 plugin to install extplugins, (3) in the new .ini configuration file format we have single key-value pairs: it will be complicated and maybe even too verbose adding a new section where to map plugin names to a download location. I t could be reintroduced if needed by imho a B3 plugin installer is the best option.
* make use of the shipped storage module to execute SQL queries in Update class
* PostgreSQL support
* revamped console setup layout (and also B3 update layout)

### CODE REVIEW

**Comment by thomasleveil** [comment]
what about deleting tests/setup_/test_download.py since its content is of no use?

**Comment by danielepantaleone** [comment]
I left it commented out because I'm not sure if everyone agrees with the removal of extplugins download from the setup procedure, in favor of a B3 plugin installer (which would need to be created together with API)

**Comment by thomasleveil** [comment]
we would need usage stats to take a decision. But AFAIK we have no mean to know how many users use the setup procedure and how many of them use the external plugin download feature.

**Comment by danielepantaleone** [comment]
I am running 28 B3s and I have never used it, but since in another issue we were discussing the fact of removing it completely in favor of a B3 config web tool and apparently someone wants to keep the console setup, I adapted it. It would need to be adapted more to produce a .ini configuration file when we will merge the .ini configuration branch.

**Comment by thomasleveil** [comment]
available in [B3 daily build 279](http://files.cucurb.net/b3/daily/)

**Pull request merged**
