### PR TITLE
plugin module structure update + postgresql/sqlite support added to status plugin

### PR DESCRIPTION
**Pull request by danielepantaleone**
This pull request implements #247. I updated the plugin module structure as explained in the issue and updated the `UpdaterPlugin` so it prefers python modules composed of `directory/__init__.py` over single python file. I also added PostgreSQL support to the status plugin which has hardcoded SQL code for schema creation, and implemented truncateTables() method in the storage module (separate methods according to the database engine being used).

I'm a bit concerned about plugin configuration filepaths though: currentl we have 2 separate paths:

* `b3/conf` for both b3.xml and plugin configuration files
* `b3/extplugins/conf` for external plugins

Wouldn't be better to have the plugin configuration file inside the plugin module directory (by default, then obviously the user can specify another path if he wants)? Something like this:

```
b3
---- plugins
-------- admin
------------ conf
---------------- plugin_admin.ini
------------ __init__.py
```

### CODE REVIEW

**Comment by thomasleveil** [comment]
> Wouldn't be better to have the plugin configuration file inside the plugin module directory (by default, then obviously the user can specify another path if he wants)?

There pro and cons for all choices we would make anyway. So I would follow the rule: *make it simple to install*. Having the conf within the plugin directory would allow the documentation to be just: _copy the directory over_ thus make it easier for most users.
Users who need to do things diffrently still can (for instance having all config files in the same folder for easy backups)

**Comment by danielepantaleone** [comment]
> make it simple to install

This is my main concern and it's the reason why I proposed this change. Recently I saw so many support requests on B3 forum of users asking why their B3 was not working: 99% of the times it was because of plugins not being installed correctly, missing plugins configuration files, broken plugins (which is the reason why I modified the plugins load routine, so now plugins cannot crash B3 anymore).

I agree with you that placing the configuration file inside the plugin directory will be a lot easier for users who do not need specific plugin configurations: just drop, load and launch B3. 

I got a question though: would this change make differences when producing the Win32 exe?

**Comment by thomasleveil** [comment]
It should not

**Comment by thomasleveil** [comment]
available in [B3 daily build 270](http://files.cucurb.net/b3/daily/)

**Pull request merged**
