### PR TITLE
escape ' characters when updating current_clients table

### PR DESCRIPTION
**Pull request by 82ndab-Bravo17**

### CODE REVIEW

**Comment by thomasleveil** [comment]
Haven't we done some changes recently regarding escaping in sql? @danielepantaleone can you give this a look?

**Comment by danielepantaleone** [comment]
I did something regarding escaping but for the `QueryBuilder` class. With pure SQL queries we would need to handle it manually. I'm not comfortable with this change to be honest, also because it will work only with MySQL and possibly with SQLite. Pure SQL impose that quoted arguments must be quoted with single quotes (even though MySQL allows double quotes). Why don't we make use of the `QueryBuilder` class here to handle SQL queries generation?

**Comment by danielepantaleone** [comment]
Looking better at the code it may actually work and due to the way data are stored in the database I don't see any other way to implement the escape here.

**Comment by thomasleveil** [comment]
good to merge then :grey_question:

**Comment by danielepantaleone** [comment]
I guess so :+1:

**Pull request merged**
