### PR TITLE
Quake 3 Arena parser + fix for OpenArena parser

### PR DESCRIPTION
**Pull request by lrq3000**
This PR adds a Quake 3 Arena parser from the OpenArena one. Should fully support Quake 3 Arena. There might be some dead code in the parser (that are only useful to OpenArena), but I'm not sure what with the recent evolutions of ioquake3.

This PR also adds optional support for ExcessivePlus mod, for both Quake 3 Arena and OpenArena.

The parser is being tested right now on a production server, please wait one or two weeks before merging (in case I need to apply a fix).

### CODE REVIEW

**Comment by danielepantaleone** [comment]
Hi there. Many thanks for this PR! I will wait until you tell me the code is stable and is available to be merged. Please do not consider Travis CI build status reporting the build as failed. Automated tests have not been updated in the last year and they won't be updated: I'm currently moving B3 source code to python 3.6 rewriting bits of the core structure (event loop, plugin structure, storage interface etc..) so I will provide automated tests for the new version (2.0??) as soon as the porting is completed (it's going to take some time though). 👍

**Comment by lrq3000** [comment]
Sorry missed your comment, but now I can confirm it works as intended, it has been running on several servers since then with no obvious issue :-) Thanks for merging!

**Comment by danielepantaleone** [comment]
No worries. Sorry for being sooo late. I have been working on porting B3 to python 3.6 in the last months (which I'm still partially doing) and I completely forgot about this one.

**Comment by lrq3000** [comment]
Ah that's great news! Yes Py3.6 is quite different, I have yet to port my own projects :p Great job!

**Pull request merged**
