### PR TITLE
Ftpytail

### PR DESCRIPTION
**Pull request by 82ndab-Bravo17**
Return values needed for log file refresh in Windows 2008 to the B3 xml file, so that a separate config file is not needed to activate it.

As originally requested, assuming it is still wanted to be this way?

### CODE REVIEW

**Comment by danielepantaleone** [comment]
Shouldn't those changes be merged?

**Comment by 82ndab-Bravo17** [comment]
Needed to make a couple of changes!

**Comment by danielepantaleone** [comment]
Could you also update debug message accordingly? https://github.com/82ndab-Bravo17/big-brother-bot/commit/6350d97847b1bdbec8c208b6c5835af1f85f18d9#diff-7230e693031e6790547733b2d7428b01R159

**Comment by 82ndab-Bravo17** [comment]
Done.

**Comment by thomasleveil** [comment]
LGTM :+1:

**Comment by thomasleveil** [comment]
available in [B3 daily build 279](http://files.cucurb.net/b3/daily/)

**Pull request merged**
