### PR TITLE
PEP8 + minor fixes

### PR DESCRIPTION
**Pull request by danielepantaleone**
Went digging a bit here: https://landscape.io/github/BigBrotherBot/big-brother-bot and managed to fix the "important" things.

### CODE REVIEW

**Comment by danielepantaleone** [comment]
Now, that's a badass comment :smiley:

**Comment by ozguruysal** [comment]
cool indeed :)

**Comment by thomasleveil** [comment]
lol ^^ I'll wait a bit before merging this because the windows server I run on AWS does not yet have the latest psycopg2 and thus would fail to build the B3 frozen windows packages

**Comment by danielepantaleone** [comment]
Well, if it can wait, I'll leave the PR as is.

**Pull request merged**
